//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuzminLanguage
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;

    public partial class Client
    {
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.Tag = new HashSet<Tag>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Birthday { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string GenderCode { get; set; }
        public string PhotoPath { get; set; }
        public string GenderTitle
        {
            get
            {
                return Gender.Name;
            }
        }
        public string FullName
        {
            get
            {
                return "ID: " + ID + " " + LastName + " " + FirstName + " " + Patronymic;
            }
        }
        public string ClientPhotoPath
        {
            get
            {
                if (string.IsNullOrEmpty(PhotoPath))
                    return GetDefaultPhotoPath();

                string fullPath = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, PhotoPath);

                if (File.Exists(fullPath))
                    return fullPath;

                return GetDefaultPhotoPath();
            }
        }
        private string GetDefaultPhotoPath()
        {
            string defaultPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Клиенты", "picture.png");
            return File.Exists(defaultPath) ? defaultPath : null;
        }
        public string ImagePath
        {
            get
            {
                if (PhotoPath == null)
                {
                    return null;
                }
                else
                {
                    return PhotoPath;
                }
            }
        }

        public string Genderous
        {
            get
            {
                if (GenderCode == "м")
                    return "Пол: м";
                else
                    return "Пол: ж";
            }
        }

        public string RegisterDateString
        {
            get
            {
                if (RegistrationDate != null)
                    return RegistrationDate.ToShortDateString();
                else
                    return "";
            }
        }
        public string BirthdayDateString
        {
            get
            {
                if (Birthday != null)
                    return Birthday.ToShortDateString();
                else
                    return "";
            }
        }
        public string LastVisitData
        {
            get
            {
                var lastVisit = ClientService.Where(p => p.ClientID == this.ID).OrderByDescending(p => p.StartTime).FirstOrDefault();
                if (lastVisit == null)
                {
                    return "нет";
                }
                else
                {
                    DateTime startTime = lastVisit.StartTime;
                    return startTime.ToShortDateString();
                }
            }
        }

        public int CountVisit
        {
            get
            {
                if (ClientService != null)
                {
                    return ClientService.Count;
                }
                return 0;
            }
        }
        public string currentnumber
        {
            get
            {
                string CurrentPhone = "7";
                for (int i = 0; i < Phone.Length; i++)
                {
                    if ((this.Phone[i] == '0') ||
                        (this.Phone[i] == '1') || (this.Phone[i] == '2') || (this.Phone[i] == '3') ||
                        (this.Phone[i] == '4') || (this.Phone[i] == '5') || (this.Phone[i] == '6') ||
                        (this.Phone[i] == '7') || (this.Phone[i] == '8') || (this.Phone[i] == '9'))
                        CurrentPhone += this.Phone[i].ToString();
                }
                return CurrentPhone;
            }
        }
        public string LastVisits
        {
            get
            {
                DateTime LastClientVisit = new DateTime(1000, 1, 1);
                foreach (ClientService ClientServices in ClientService)
                {
                    if (ClientServices.StartTime > LastClientVisit)
                        LastClientVisit = ClientServices.StartTime;
                }
                if (LastClientVisit > new DateTime(1000, 1, 1))
                    return LastClientVisit.ToString();
                else
                    return "Не посещал(а)";
            }
        }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<ClientService> ClientService { get; set; }
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
