//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuzminLanguage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.Tag = new HashSet<Tag>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Birthday { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string GenderCode { get; set; }
        public string PhotoPath { get; set; }
        public string FullName
        {
            get
            {
                return "ID: " + ID + " " + LastName + " " + FirstName + " " + Patronymic;
            }
        }

        public string ImagePath
        {
            get
            {
                if (PhotoPath == null)
                {
                    return null;
                }
                else
                {
                    return PhotoPath;
                }
            }
        }

        public string Genderous
        {
            get
            {
                if (GenderCode == "м")
                    return "Пол: м";
                else
                    return "Пол: ж";
            }
        }

        public string RegisterDateString
        {
            get
            {
                if (RegistrationDate != null)
                    return RegistrationDate.ToShortDateString();
                else
                    return "";
            }
        }
        public string BirthdayDateString
        {
            get
            {
                if (Birthday != null)
                    return Birthday.ToShortDateString();
                else
                    return "";
            }
        }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<ClientService> ClientService { get; set; }
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
